<?php

// File generated from our OpenAPI spec

namespace DRStripe\Util;

class ObjectTypes
{
    /**
     * @var array Mapping from object types to resource classes
     */
    const mapping = [
        \DRStripe\Account::OBJECT_NAME => \DRStripe\Account::class,
        \DRStripe\AccountLink::OBJECT_NAME => \DRStripe\AccountLink::class,
        \DRStripe\AlipayAccount::OBJECT_NAME => \DRStripe\AlipayAccount::class,
        \DRStripe\ApplePayDomain::OBJECT_NAME => \DRStripe\ApplePayDomain::class,
        \DRStripe\ApplicationFee::OBJECT_NAME => \DRStripe\ApplicationFee::class,
        \DRStripe\ApplicationFeeRefund::OBJECT_NAME => \DRStripe\ApplicationFeeRefund::class,
        \DRStripe\Apps\Secret::OBJECT_NAME => \DRStripe\Apps\Secret::class,
        \DRStripe\Balance::OBJECT_NAME => \DRStripe\Balance::class,
        \DRStripe\BalanceTransaction::OBJECT_NAME => \DRStripe\BalanceTransaction::class,
        \DRStripe\BankAccount::OBJECT_NAME => \DRStripe\BankAccount::class,
        \DRStripe\BillingPortal\Configuration::OBJECT_NAME => \DRStripe\BillingPortal\Configuration::class,
        \DRStripe\BillingPortal\Session::OBJECT_NAME => \DRStripe\BillingPortal\Session::class,
        \DRStripe\BitcoinReceiver::OBJECT_NAME => \DRStripe\BitcoinReceiver::class,
        \DRStripe\BitcoinTransaction::OBJECT_NAME => \DRStripe\BitcoinTransaction::class,
        \DRStripe\Capability::OBJECT_NAME => \DRStripe\Capability::class,
        \DRStripe\Card::OBJECT_NAME => \DRStripe\Card::class,
        \DRStripe\CashBalance::OBJECT_NAME => \DRStripe\CashBalance::class,
        \DRStripe\Charge::OBJECT_NAME => \DRStripe\Charge::class,
        \DRStripe\Checkout\Session::OBJECT_NAME => \DRStripe\Checkout\Session::class,
        \DRStripe\Collection::OBJECT_NAME => \DRStripe\Collection::class,
        \DRStripe\CountrySpec::OBJECT_NAME => \DRStripe\CountrySpec::class,
        \DRStripe\Coupon::OBJECT_NAME => \DRStripe\Coupon::class,
        \DRStripe\CreditNote::OBJECT_NAME => \DRStripe\CreditNote::class,
        \DRStripe\CreditNoteLineItem::OBJECT_NAME => \DRStripe\CreditNoteLineItem::class,
        \DRStripe\Customer::OBJECT_NAME => \DRStripe\Customer::class,
        \DRStripe\CustomerBalanceTransaction::OBJECT_NAME => \DRStripe\CustomerBalanceTransaction::class,
        \DRStripe\Discount::OBJECT_NAME => \DRStripe\Discount::class,
        \DRStripe\Dispute::OBJECT_NAME => \DRStripe\Dispute::class,
        \DRStripe\EphemeralKey::OBJECT_NAME => \DRStripe\EphemeralKey::class,
        \DRStripe\Event::OBJECT_NAME => \DRStripe\Event::class,
        \DRStripe\ExchangeRate::OBJECT_NAME => \DRStripe\ExchangeRate::class,
        \DRStripe\File::OBJECT_NAME => \DRStripe\File::class,
        \DRStripe\File::OBJECT_NAME_ALT => \DRStripe\File::class,
        \DRStripe\FileLink::OBJECT_NAME => \DRStripe\FileLink::class,
        \DRStripe\FinancialConnections\Account::OBJECT_NAME => \DRStripe\FinancialConnections\Account::class,
        \DRStripe\FinancialConnections\AccountOwner::OBJECT_NAME => \DRStripe\FinancialConnections\AccountOwner::class,
        \DRStripe\FinancialConnections\AccountOwnership::OBJECT_NAME => \DRStripe\FinancialConnections\AccountOwnership::class,
        \DRStripe\FinancialConnections\Session::OBJECT_NAME => \DRStripe\FinancialConnections\Session::class,
        \DRStripe\FundingInstructions::OBJECT_NAME => \DRStripe\FundingInstructions::class,
        \DRStripe\Identity\VerificationReport::OBJECT_NAME => \DRStripe\Identity\VerificationReport::class,
        \DRStripe\Identity\VerificationSession::OBJECT_NAME => \DRStripe\Identity\VerificationSession::class,
        \DRStripe\Invoice::OBJECT_NAME => \DRStripe\Invoice::class,
        \DRStripe\InvoiceItem::OBJECT_NAME => \DRStripe\InvoiceItem::class,
        \DRStripe\InvoiceLineItem::OBJECT_NAME => \DRStripe\InvoiceLineItem::class,
        \DRStripe\Issuing\Authorization::OBJECT_NAME => \DRStripe\Issuing\Authorization::class,
        \DRStripe\Issuing\Card::OBJECT_NAME => \DRStripe\Issuing\Card::class,
        \DRStripe\Issuing\CardDetails::OBJECT_NAME => \DRStripe\Issuing\CardDetails::class,
        \DRStripe\Issuing\Cardholder::OBJECT_NAME => \DRStripe\Issuing\Cardholder::class,
        \DRStripe\Issuing\Dispute::OBJECT_NAME => \DRStripe\Issuing\Dispute::class,
        \DRStripe\Issuing\Transaction::OBJECT_NAME => \DRStripe\Issuing\Transaction::class,
        \DRStripe\LineItem::OBJECT_NAME => \DRStripe\LineItem::class,
        \DRStripe\LoginLink::OBJECT_NAME => \DRStripe\LoginLink::class,
        \DRStripe\Mandate::OBJECT_NAME => \DRStripe\Mandate::class,
        \DRStripe\Order::OBJECT_NAME => \DRStripe\Order::class,
        \DRStripe\PaymentIntent::OBJECT_NAME => \DRStripe\PaymentIntent::class,
        \DRStripe\PaymentLink::OBJECT_NAME => \DRStripe\PaymentLink::class,
        \DRStripe\PaymentMethod::OBJECT_NAME => \DRStripe\PaymentMethod::class,
        \DRStripe\Payout::OBJECT_NAME => \DRStripe\Payout::class,
        \DRStripe\Person::OBJECT_NAME => \DRStripe\Person::class,
        \DRStripe\Plan::OBJECT_NAME => \DRStripe\Plan::class,
        \DRStripe\Price::OBJECT_NAME => \DRStripe\Price::class,
        \DRStripe\Product::OBJECT_NAME => \DRStripe\Product::class,
        \DRStripe\PromotionCode::OBJECT_NAME => \DRStripe\PromotionCode::class,
        \DRStripe\Quote::OBJECT_NAME => \DRStripe\Quote::class,
        \DRStripe\Radar\EarlyFraudWarning::OBJECT_NAME => \DRStripe\Radar\EarlyFraudWarning::class,
        \DRStripe\Radar\ValueList::OBJECT_NAME => \DRStripe\Radar\ValueList::class,
        \DRStripe\Radar\ValueListItem::OBJECT_NAME => \DRStripe\Radar\ValueListItem::class,
        \DRStripe\Recipient::OBJECT_NAME => \DRStripe\Recipient::class,
        \DRStripe\RecipientTransfer::OBJECT_NAME => \DRStripe\RecipientTransfer::class,
        \DRStripe\Refund::OBJECT_NAME => \DRStripe\Refund::class,
        \DRStripe\Reporting\ReportRun::OBJECT_NAME => \DRStripe\Reporting\ReportRun::class,
        \DRStripe\Reporting\ReportType::OBJECT_NAME => \DRStripe\Reporting\ReportType::class,
        \DRStripe\Review::OBJECT_NAME => \DRStripe\Review::class,
        \DRStripe\SearchResult::OBJECT_NAME => \DRStripe\SearchResult::class,
        \DRStripe\SetupAttempt::OBJECT_NAME => \DRStripe\SetupAttempt::class,
        \DRStripe\SetupIntent::OBJECT_NAME => \DRStripe\SetupIntent::class,
        \DRStripe\ShippingRate::OBJECT_NAME => \DRStripe\ShippingRate::class,
        \DRStripe\Sigma\ScheduledQueryRun::OBJECT_NAME => \DRStripe\Sigma\ScheduledQueryRun::class,
        \DRStripe\SKU::OBJECT_NAME => \DRStripe\SKU::class,
        \DRStripe\Source::OBJECT_NAME => \DRStripe\Source::class,
        \DRStripe\SourceTransaction::OBJECT_NAME => \DRStripe\SourceTransaction::class,
        \DRStripe\Subscription::OBJECT_NAME => \DRStripe\Subscription::class,
        \DRStripe\SubscriptionItem::OBJECT_NAME => \DRStripe\SubscriptionItem::class,
        \DRStripe\SubscriptionSchedule::OBJECT_NAME => \DRStripe\SubscriptionSchedule::class,
        \DRStripe\TaxCode::OBJECT_NAME => \DRStripe\TaxCode::class,
        \DRStripe\TaxId::OBJECT_NAME => \DRStripe\TaxId::class,
        \DRStripe\TaxRate::OBJECT_NAME => \DRStripe\TaxRate::class,
        \DRStripe\Terminal\Configuration::OBJECT_NAME => \DRStripe\Terminal\Configuration::class,
        \DRStripe\Terminal\ConnectionToken::OBJECT_NAME => \DRStripe\Terminal\ConnectionToken::class,
        \DRStripe\Terminal\Location::OBJECT_NAME => \DRStripe\Terminal\Location::class,
        \DRStripe\Terminal\Reader::OBJECT_NAME => \DRStripe\Terminal\Reader::class,
        \DRStripe\TestHelpers\TestClock::OBJECT_NAME => \DRStripe\TestHelpers\TestClock::class,
        \DRStripe\ThreeDSecure::OBJECT_NAME => \DRStripe\ThreeDSecure::class,
        \DRStripe\Token::OBJECT_NAME => \DRStripe\Token::class,
        \DRStripe\Topup::OBJECT_NAME => \DRStripe\Topup::class,
        \DRStripe\Transfer::OBJECT_NAME => \DRStripe\Transfer::class,
        \DRStripe\TransferReversal::OBJECT_NAME => \DRStripe\TransferReversal::class,
        \DRStripe\Treasury\CreditReversal::OBJECT_NAME => \DRStripe\Treasury\CreditReversal::class,
        \DRStripe\Treasury\DebitReversal::OBJECT_NAME => \DRStripe\Treasury\DebitReversal::class,
        \DRStripe\Treasury\FinancialAccount::OBJECT_NAME => \DRStripe\Treasury\FinancialAccount::class,
        \DRStripe\Treasury\FinancialAccountFeatures::OBJECT_NAME => \DRStripe\Treasury\FinancialAccountFeatures::class,
        \DRStripe\Treasury\InboundTransfer::OBJECT_NAME => \DRStripe\Treasury\InboundTransfer::class,
        \DRStripe\Treasury\OutboundPayment::OBJECT_NAME => \DRStripe\Treasury\OutboundPayment::class,
        \DRStripe\Treasury\OutboundTransfer::OBJECT_NAME => \DRStripe\Treasury\OutboundTransfer::class,
        \DRStripe\Treasury\ReceivedCredit::OBJECT_NAME => \DRStripe\Treasury\ReceivedCredit::class,
        \DRStripe\Treasury\ReceivedDebit::OBJECT_NAME => \DRStripe\Treasury\ReceivedDebit::class,
        \DRStripe\Treasury\Transaction::OBJECT_NAME => \DRStripe\Treasury\Transaction::class,
        \DRStripe\Treasury\TransactionEntry::OBJECT_NAME => \DRStripe\Treasury\TransactionEntry::class,
        \DRStripe\UsageRecord::OBJECT_NAME => \DRStripe\UsageRecord::class,
        \DRStripe\UsageRecordSummary::OBJECT_NAME => \DRStripe\UsageRecordSummary::class,
        \DRStripe\WebhookEndpoint::OBJECT_NAME => \DRStripe\WebhookEndpoint::class,
    ];
}
